[package]
name = "api_docs_generator"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
